name: AdventOfCode2021
version: 0.1.0.0
github: "shepherdjerred/advent-of-code-2021"
license: "GPL-3.0"
author: "Jerred Shepherd"
maintainer: "shepherdjerred@gmail.com"
copyright: "2021 Jerred Shepherd"

extra-source-files:
  - README.md

description: My solutions to Advent of Code 2021

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Day1:
    main: Main.hs
    source-dirs: Day1
  Day2:
    main: Main.hs
    source-dirs: Day2
  Day3:
    main: Main.hs
    source-dirs: Day3
  Day4:
    main: Main.hs
    source-dirs: Day4
