on: [push]
name: Haskell
jobs:
  haskell:
    name: Build Haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: "9.2.1"
          cabal-version: "3.6.0.0"
          enable-stack: true
          stack-version: "2.7.3"
      - run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
