name: Update README ⭐
on:
  schedule:
    - cron: "32 */4 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 471518
          sessionCookie: ${{ secrets.AOC_SESSION }}
          year: 2021
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
